name: Staging Deployment

on: 
  repository_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies (if not in cache)
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }} CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }} npm run build

      - name: Deploy to now
        run: VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} npm run deploy:dev
  
  
